# Generated by Django 5.0.6 on 2024-05-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_tutor', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('nome_do_animal', models.CharField(max_length=100)),
                ('tipo_de_animal', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaro', 'Pássaro'), ('Hamster', 'Hasmster'), ('Coelho', 'Coelho'), ('Outro', 'Outro')], max_length=50)),
                ('idade_do_animal', models.CharField(max_length=50)),
                ('peso_do_animal', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
