# Generated by Django 5.0.6 on 2024-05-31 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamento_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 8, 8, 36, 689410)),
            preserve_default=False,
        ),
    ]
