# Generated by Django 5.0.6 on 2024-05-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_agendamento_data_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='data_horario',
        ),
    ]
